name: gitCommitLog
run-name: ${{ github.repository }} commit log
on: [ push ]
jobs:
  pullAndCommitLog:
    runs-on: self-hosted
    steps:
      - run: "cd /Users/ubuntu/robot; git pull;"
      - run: "cd /Users/ubuntu/robot; node robot.js gitLogToJson;"

